[package]
name = "lolita"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt = { version = "0.37", features = ["substrate-compat"] }
pallet-identity = { version = "38" }
tokio = { version = "1", features = ["full"] }
blake2 = "0.10"
parity-scale-codec = "3.0"
sp-core = "34.0.0"
hex = "0.4"
